language: python
sudo: false
python:
    - "3.5"
    - "3.6"
    - "nightly"
install:
    - pip install -r requirements.txt
    - pip install coverage coveralls
script:
    - coverage run -m unittest
after_success:
    coveralls
